arb-dir: lib/l10n
template-arb-file: app_en.arb
# Генеруємо прямо в lib/l10n, щоб імпорт лишився таким, як у тебе
output-dir: lib/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
